# Generated by Django 6.0 on 2026-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('glucose', 'Glucose'), ('steps', 'Steps'), ('calories', 'Calories'), ('oxygen', 'Oxygen'), ('weight', 'Weight')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('reminder', 'Reminder'), ('info', 'Info'), ('report', 'Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_device_id', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heart_ecg', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_afib', models.BooleanField(blank=True, null=True)),
                ('heart_hrv_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heart_rr_interval_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bp_device_id', models.IntegerField(blank=True, null=True)),
                ('bp_systolic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bp_diastolic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bp_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bp_pulse_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bp_irregular', models.BooleanField(blank=True, null=True)),
                ('bp_body_position', models.CharField(blank=True, max_length=50, null=True)),
                ('glucose_device_id', models.IntegerField(blank=True, null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('glucose_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('glucose_hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('glucose_fasting', models.BooleanField(blank=True, null=True)),
                ('calories_device_id', models.IntegerField(blank=True, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basal_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metabolic_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('steps_device_id', models.IntegerField(blank=True, null=True)),
                ('steps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_steps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('step_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('walking_pace', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cadence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floors_climbed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oxygen_device_id', models.IntegerField(blank=True, null=True)),
                ('oxygen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vo2_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respiration_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oxygen_variability', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sleep_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('sleep_duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sleep_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skin_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'readings_draft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('glucose', 'Glucose'), ('steps', 'Steps'), ('calories', 'Calories'), ('oxygen', 'Oxygen'), ('weight', 'Weight'), ('bmi', 'BMI')], max_length=20)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('equal', 'Equal')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'thresholds',
                'managed': False,
            },
        ),
    ]
